title: My Portfolio
description: Welcome to my portfolio website.
theme: minima
baseurl: "" # If your site is at https://username.github.io/, leave it empty
# baseurl: "/my-portfolio" # If your site is at https://username.github.io/my-portfolio/
